In [19]:
import pandas as pd
df = pd.read_csv("../data/raw/House_Prices.csv")
df = df.iloc[:1460].copy()

In [20]:
df = df.drop(columns="Id")
df["MSSubClass"] = df["MSSubClass"].astype("str")

In [21]:
df.shape

(1460, 80)

the data contains 2919 houses and 80 feature

In [22]:
df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice'],
      dtype='str')

the dataset contains many features describing the house : its locations , size , quality, age , rooms, garage, outdoor areas and sate info 
the target is SatePrice

In [23]:
pd.set_option('display.max_rows', None)
df.dtypes

MSSubClass           str
MSZoning             str
LotFrontage      float64
LotArea            int64
Street               str
Alley                str
LotShape             str
LandContour          str
Utilities            str
LotConfig            str
LandSlope            str
Neighborhood         str
Condition1           str
Condition2           str
BldgType             str
HouseStyle           str
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
RoofStyle            str
RoofMatl             str
Exterior1st          str
Exterior2nd          str
MasVnrType           str
MasVnrArea       float64
ExterQual            str
ExterCond            str
Foundation           str
BsmtQual             str
BsmtCond             str
BsmtExposure         str
BsmtFinType1         str
BsmtFinSF1       float64
BsmtFinType2         str
BsmtFinSF2       float64
BsmtUnfSF        float64
TotalBsmtSF      float64
Heating              str
HeatingQC            str
CentralAir           str
Electrical           str
1stFlrSF           int64
2ndFlrSF           int64
LowQualFinSF       int64
GrLivArea          int64
BsmtFullBath     float64
BsmtHalfBath     float64
FullBath           int64
HalfBath           int64
BedroomAbvGr       int64
KitchenAbvGr       int64
KitchenQual          str
TotRmsAbvGrd       int64
Functional           str
Fireplaces         int64
FireplaceQu          str
GarageType           str
GarageYrBlt      float64
GarageFinish         str
GarageCars       float64
GarageArea       float64
GarageQual           str
GarageCond           str
PavedDrive           str
WoodDeckSF         int64
OpenPorchSF        int64
EnclosedPorch      int64
3SsnPorch          int64
ScreenPorch        int64
PoolArea           int64
PoolQC               str
Fence                str
MiscFeature          str
MiscVal            int64
MoSold             int64
YrSold             int64
SaleType             str
SaleCondition        str
SalePrice        float64
dtype: object

the df contains both numirical and categorical features

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   str
 1   MSZoning       1460 non-null   str
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   str
 5   Alley          91 non-null     str
 6   LotShape       1460 non-null   str
 7   LandContour    1460 non-null   str
 8   Utilities      1460 non-null   str
 9   LotConfig      1460 non-null   str
 10  LandSlope      1460 non-null   str
 11  Neighborhood   1460 non-null   str
 12  Condition1     1460 non-null   str
 13  Condition2     1460 non-null   str
 14  BldgType       1460 non-null   str
 15  HouseStyle     1460 non-null   str
 16  OverallQual    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  YearBuilt      1460 non-null   int64
 19  YearRemodAdd   1460 non-null   int64
 20  RoofStyle      1460 non-null   str
 21  RoofMatl       1460 non-null   str
 22  Exterior1st    1460 non-null   str
 23  Exterior2nd    1460 non-null   str
 24  MasVnrType     588 non-null    str
 25  MasVnrArea     1452 non-null   float64
 26  ExterQual      1460 non-null   str
 27  ExterCond      1460 non-null   str
 28  Foundation     1460 non-null   str
 29  BsmtQual       1423 non-null   str
 30  BsmtCond       1423 non-null   str
 31  BsmtExposure   1422 non-null   str
 32  BsmtFinType1   1423 non-null   str
 33  BsmtFinSF1     1460 non-null   float64
 34  BsmtFinType2   1422 non-null   str
 35  BsmtFinSF2     1460 non-null   float64
 36  BsmtUnfSF      1460 non-null   float64
 37  TotalBsmtSF    1460 non-null   float64
 38  Heating        1460 non-null   str
 39  HeatingQC      1460 non-null   str
 40  CentralAir     1460 non-null   str
 41  Electrical     1459 non-null   str
 42  1stFlrSF       1460 non-null   int64
 43  2ndFlrSF       1460 non-null   int64
 44  LowQualFinSF   1460 non-null   int64
 45  GrLivArea      1460 non-null   int64
 46  BsmtFullBath   1460 non-null   float64
 47  BsmtHalfBath   1460 non-null   float64
 48  FullBath       1460 non-null   int64
 49  HalfBath       1460 non-null   int64
 50  BedroomAbvGr   1460 non-null   int64
 51  KitchenAbvGr   1460 non-null   int64
 52  KitchenQual    1460 non-null   str
 53  TotRmsAbvGrd   1460 non-null   int64
 54  Functional     1460 non-null   str
 55  Fireplaces     1460 non-null   int64
 56  FireplaceQu    770 non-null    str
 57  GarageType     1379 non-null   str
 58  GarageYrBlt    1379 non-null   float64
 59  GarageFinish   1379 non-null   str
 60  GarageCars     1460 non-null   float64
 61  GarageArea     1460 non-null   float64
 62  GarageQual     1379 non-null   str
 63  GarageCond     1379 non-null   str
 64  PavedDrive     1460 non-null   str
 65  WoodDeckSF     1460 non-null   int64
 66  OpenPorchSF    1460 non-null   int64
 67  EnclosedPorch  1460 non-null   int64
 68  3SsnPorch      1460 non-null   int64
 69  ScreenPorch    1460 non-null   int64
 70  PoolArea       1460 non-null   int64
 71  PoolQC         7 non-null      str
 72  Fence          281 non-null    str
 73  MiscFeature    54 non-null     str
 74  MiscVal        1460 non-null   int64
 75  MoSold         1460 non-null   int64
 76  YrSold         1460 non-null   int64
 77  SaleType       1460 non-null   str
 78  SaleCondition  1460 non-null   str
 79  SalePrice      1460 non-null   float64
dtypes: float64(12), int64(24), str(44)
memory usage: 1.1 MB

several columns contain missing values such : lotfrontage and alley

In [25]:
df.isna().sum()

MSSubClass          0
MSZoning            0
LotFrontage       259
LotArea             0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType        872
MasVnrArea          8
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinSF1          0
BsmtFinType2       38
BsmtFinSF2          0
BsmtUnfSF           0
TotalBsmtSF         0
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        0
BsmtHalfBath        0
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         0
TotRmsAbvGrd        0
Functional          0
Fireplaces          0
FireplaceQu       690
GarageType         81
GarageYrBlt        81
GarageFinish       81
GarageCars          0
GarageArea          0
GarageQual         81
GarageCond         81
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1453
Fence            1179
MiscFeature      1406
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice           0
dtype: int64

In [26]:
missing_values = df.isna().sum()

missing_values[missing_values > 0].sort_values(ascending=False)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
MasVnrType       872
FireplaceQu      690
LotFrontage      259
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
BsmtExposure      38
BsmtFinType2      38
BsmtQual          37
BsmtCond          37
BsmtFinType1      37
MasVnrArea         8
Electrical         1
dtype: int64

the datasets contains many missing values columns: some has very high percentage of missing data: poolQC , miscfeature , alley , fence ... others has a low percentage of missing date different strategies will be needed during data processing

In [27]:
df.duplicated().sum()

np.int64(0)

no duplicateds rows found in the data

In [28]:
df.describe()

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,1460.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,46.549315,567.240411,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,161.319273,441.866955,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,0.000000,223.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,0.000000,477.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,0.000000,808.000000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1474.000000,2336.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

The numerical features have very different ranges: Some columns show large extreme values, such as LotArea, which may indicate outliers. SalePrice ranges from 34 900 to 755 000, with a median around 176 735

In [29]:
numeric_cols = df.select_dtypes(include="number").columns
categorical_cols = df.select_dtypes(exclude="number").columns

In [30]:
numeric_cols
#len(numeric_cols)

Index(['LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt',
       'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF',
       'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea',
       'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr',
       'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt',
       'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal',
       'MoSold', 'YrSold', 'SalePrice'],
      dtype='str')

the dataset contains 38 numirical columns , most represent numirical values , but some are categorical codes and may require special handling

In [31]:
categorical_cols
#len(categorical_cols)

Index(['MSSubClass', 'MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour',
       'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1',
       'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl',
       'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond',
       'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
       'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical',
       'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType',
       'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC',
       'Fence', 'MiscFeature', 'SaleType', 'SaleCondition'],
      dtype='str')

The dataset contains 43 categorical columns. Most of them will need to be encoded into numerical values before they can be used by the Machine Learning models

In [32]:
df["SalePrice"].describe()

count      1460.000000
mean     180921.195890
std       79442.502883
min       34900.000000
25%      129975.000000
50%      163000.000000
75%      214000.000000
max      755000.000000
Name: SalePrice, dtype: float64

SalePrice has an average value of about 180,053 and a median of about 176,735. Prices range from 34,900 to 755,000, which shows a wide spread and suggests the presence of some high-price extreme values.

In [33]:
for col in categorical_cols:
    print(col, df[col].unique()[:20])

MSSubClass <ArrowStringArray>
[ '60',  '20',  '70',  '50', '190',  '45',  '90', '120',  '30',  '85',  '80',
 '160',  '75', '180',  '40']
Length: 15, dtype: str
MSZoning <ArrowStringArray>
['RL', 'RM', 'C (all)', 'FV', 'RH']
Length: 5, dtype: str
Street <ArrowStringArray>
['Pave', 'Grvl']
Length: 2, dtype: str
Alley <ArrowStringArray>
[nan, 'Grvl', 'Pave']
Length: 3, dtype: str
LotShape <ArrowStringArray>
['Reg', 'IR1', 'IR2', 'IR3']
Length: 4, dtype: str
LandContour <ArrowStringArray>
['Lvl', 'Bnk', 'Low', 'HLS']
Length: 4, dtype: str
Utilities <ArrowStringArray>
['AllPub', 'NoSeWa']
Length: 2, dtype: str
LotConfig <ArrowStringArray>
['Inside', 'FR2', 'Corner', 'CulDSac', 'FR3']
Length: 5, dtype: str
LandSlope <ArrowStringArray>
['Gtl', 'Mod', 'Sev']
Length: 3, dtype: str
Neighborhood <ArrowStringArray>
['CollgCr', 'Veenker', 'Crawfor', 'NoRidge', 'Mitchel', 'Somerst',  'NWAmes',
 'OldTown', 'BrkSide',  'Sawyer', 'NridgHt',   'NAmes', 'SawyerW',  'IDOTRR',
 'MeadowV', 'Edwards',  'Timber', 'Gilbert', 'StoneBr', 'ClearCr']
Length: 20, dtype: str
Condition1 <ArrowStringArray>
['Norm', 'Feedr', 'PosN', 'Artery', 'RRAe', 'RRNn', 'RRAn', 'PosA', 'RRNe']
Length: 9, dtype: str
Condition2 <ArrowStringArray>
['Norm', 'Artery', 'RRNn', 'Feedr', 'PosN', 'PosA', 'RRAn', 'RRAe']
Length: 8, dtype: str
BldgType <ArrowStringArray>
['1Fam', '2fmCon', 'Duplex', 'TwnhsE', 'Twnhs']
Length: 5, dtype: str
HouseStyle <ArrowStringArray>
['2Story', '1Story', '1.5Fin', '1.5Unf', 'SFoyer', 'SLvl', '2.5Unf', '2.5Fin']
Length: 8, dtype: str
RoofStyle <ArrowStringArray>
['Gable', 'Hip', 'Gambrel', 'Mansard', 'Flat', 'Shed']
Length: 6, dtype: str
RoofMatl <ArrowStringArray>
['CompShg', 'WdShngl',   'Metal', 'WdShake', 'Membran', 'Tar&Grv',    'Roll',
 'ClyTile']
Length: 8, dtype: str
Exterior1st <ArrowStringArray>
['VinylSd', 'MetalSd', 'Wd Sdng', 'HdBoard', 'BrkFace', 'WdShing', 'CemntBd',
 'Plywood', 'AsbShng',  'Stucco', 'BrkComm', 'AsphShn',   'Stone', 'ImStucc',
  'CBlock']
Length: 15, dtype: str
Exterior2nd <ArrowStringArray>
['VinylSd', 'MetalSd', 'Wd Shng', 'HdBoard', 'Plywood', 'Wd Sdng', 'CmentBd',
 'BrkFace',  'Stucco', 'AsbShng', 'Brk Cmn', 'ImStucc', 'AsphShn',   'Stone',
   'Other',  'CBlock']
Length: 16, dtype: str
MasVnrType <ArrowStringArray>
['BrkFace', nan, 'Stone', 'BrkCmn']
Length: 4, dtype: str
ExterQual <ArrowStringArray>
['Gd', 'TA', 'Ex', 'Fa']
Length: 4, dtype: str
ExterCond <ArrowStringArray>
['TA', 'Gd', 'Fa', 'Po', 'Ex']
Length: 5, dtype: str
Foundation <ArrowStringArray>
['PConc', 'CBlock', 'BrkTil', 'Wood', 'Slab', 'Stone']
Length: 6, dtype: str
BsmtQual <ArrowStringArray>
['Gd', 'TA', 'Ex', nan, 'Fa']
Length: 5, dtype: str
BsmtCond <ArrowStringArray>
['TA', 'Gd', nan, 'Fa', 'Po']
Length: 5, dtype: str
BsmtExposure <ArrowStringArray>
['No', 'Gd', 'Mn', 'Av', nan]
Length: 5, dtype: str
BsmtFinType1 <ArrowStringArray>
['GLQ', 'ALQ', 'Unf', 'Rec', 'BLQ', nan, 'LwQ']
Length: 7, dtype: str
BsmtFinType2 <ArrowStringArray>
['Unf', 'BLQ', nan, 'ALQ', 'Rec', 'LwQ', 'GLQ']
Length: 7, dtype: str
Heating <ArrowStringArray>
['GasA', 'GasW', 'Grav', 'Wall', 'OthW', 'Floor']
Length: 6, dtype: str
HeatingQC <ArrowStringArray>
['Ex', 'Gd', 'TA', 'Fa', 'Po']
Length: 5, dtype: str
CentralAir <ArrowStringArray>
['Y', 'N']
Length: 2, dtype: str
Electrical <ArrowStringArray>
['SBrkr', 'FuseF', 'FuseA', 'FuseP', 'Mix', nan]
Length: 6, dtype: str
KitchenQual <ArrowStringArray>
['Gd', 'TA', 'Ex', 'Fa']
Length: 4, dtype: str
Functional <ArrowStringArray>
['Typ', 'Min1', 'Maj1', 'Min2', 'Mod', 'Maj2', 'Sev']
Length: 7, dtype: str
FireplaceQu <ArrowStringArray>
[nan, 'TA', 'Gd', 'Fa', 'Ex', 'Po']
Length: 6, dtype: str
GarageType <ArrowStringArray>
['Attchd', 'Detchd', 'BuiltIn', 'CarPort', nan, 'Basment', '2Types']
Length: 7, dtype: str
GarageFinish <ArrowStringArray>
['RFn', 'Unf', 'Fin', nan]
Length: 4, dtype: str
GarageQual <ArrowStringArray>
['TA', 'Fa', 'Gd', nan, 'Ex', 'Po']
Length: 6, dtype: str
GarageCond <ArrowStringArray>
['TA', 'Fa', nan, 'Gd', 'Po', 'Ex']
Length: 6, dtype: str
PavedDrive <ArrowStringArray>
['Y', 'N', 'P']
Length: 3, dtype: str
PoolQC <ArrowStringArray>
[nan, 'Ex', 'Fa', 'Gd']
Length: 4, dtype: str
Fence <ArrowStringArray>
[nan, 'MnPrv', 'GdWo', 'GdPrv', 'MnWw']
Length: 5, dtype: str
MiscFeature <ArrowStringArray>
[nan, 'Shed', 'Gar2', 'Othr', 'TenC']
Length: 5, dtype: str
SaleType <ArrowStringArray>
['WD', 'New', 'COD', 'ConLD', 'ConLI', 'CWD', 'ConLw', 'Con', 'Oth']
Length: 9, dtype: str
SaleCondition <ArrowStringArray>
['Normal', 'Abnorml', 'Partial', 'AdjLand', 'Alloca', 'Family']
Length: 6, dtype: str

No obvious inconsistencies were found in the categorical values. Most values appear to use consistent category codes. Some categorical columns contain missing values NaN, which will be handled during preprocessing

In [34]:
df[numeric_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
LotFrontage,1201.0,70.049958,24.284752,21.0,59.00,69.0,80.00,313.0
LotArea,1460.0,10516.828082,9981.264932,1300.0,7553.50,9478.5,11601.50,215245.0
OverallQual,1460.0,6.099315,1.382997,1.0,5.00,6.0,7.00,10.0
OverallCond,1460.0,5.575342,1.112799,1.0,5.00,5.0,6.00,9.0
YearBuilt,1460.0,1971.267808,30.202904,1872.0,1954.00,1973.0,2000.00,2010.0
YearRemodAdd,1460.0,1984.865753,20.645407,1950.0,1967.00,1994.0,2004.00,2010.0
MasVnrArea,1452.0,103.685262,181.066207,0.0,0.00,0.0,166.00,1600.0
BsmtFinSF1,1460.0,443.639726,456.098091,0.0,0.00,383.5,712.25,5644.0
BsmtFinSF2,1460.0,46.549315,161.319273,0.0,0.00,0.0,0.00,1474.0
BsmtUnfSF,1460.0,567.240411,441.866955,0.0,223.00,477.5,808.00,2336.0
TotalBsmtSF,1460.0,1057.429452,438.705324,0.0,795.75,991.5,1298.25,6110.0
1stFlrSF,1460.0,1162.626712,386.587738,334.0,882.00,1087.0,1391.25,4692.0
2ndFlrSF,1460.0,346.992466,436.528436,0.0,0.00,0.0,728.00,2065.0
LowQualFinSF,1460.0,5.844521,48.623081,0.0,0.00,0.0,0.00,572.0
GrLivArea,1460.0,1515.463699,525.480383,334.0,1129.50,1464.0,1776.75,5642.0
BsmtFullBath,1460.0,0.425342,0.518911,0.0,0.00,0.0,1.00,3.0
BsmtHalfBath,1460.0,0.057534,0.238753,0.0,0.00,0.0,0.00,2.0
FullBath,1460.0,1.565068,0.550916,0.0,1.00,2.0,2.00,3.0
HalfBath,1460.0,0.382877,0.502885,0.0,0.00,0.0,1.00,2.0
BedroomAbvGr,1460.0,2.866438,0.815778,0.0,2.00,3.0,3.00,8.0
KitchenAbvGr,1460.0,1.046575,0.220338,0.0,1.00,1.0,1.00,3.0
TotRmsAbvGrd,1460.0,6.517808,1.625393,2.0,5.00,6.0,7.00,14.0
Fireplaces,1460.0,0.613014,0.644666,0.0,0.00,1.0,1.00,3.0
GarageYrBlt,1379.0,1978.506164,24.689725,1900.0,1961.00,1980.0,2002.00,2010.0
GarageCars,1460.0,1.767123,0.747315,0.0,1.00,2.0,2.00,4.0
GarageArea,1460.0,472.980137,213.804841,0.0,334.50,480.0,576.00,1418.0
WoodDeckSF,1460.0,94.244521,125.338794,0.0,0.00,0.0,168.00,857.0
OpenPorchSF,1460.0,46.660274,66.256028,0.0,0.00,25.0,68.00,547.0
EnclosedPorch,1460.0,21.954110,61.119149,0.0,0.00,0.0,0.00,552.0
3SsnPorch,1460.0,3.409589,29.317331,0.0,0.00,0.0,0.00,508.0
ScreenPorch,1460.0,15.060959,55.757415,0.0,0.00,0.0,0.00,480.0
PoolArea,1460.0,2.758904,40.177307,0.0,0.00,0.0,0.00,738.0
MiscVal,1460.0,43.489041,496.123024,0.0,0.00,0.0,0.00,15500.0
MoSold,1460.0,6.321918,2.703626,1.0,5.00,6.0,8.00,12.0
YrSold,1460.0,2007.815753,1.328095,2006.0,2007.00,2008.0,2009.00,2010.0
SalePrice,1460.0,180921.195890,79442.502883,34900.0,129975.00,163000.0,214000.00,755000.0

Several numerical features contain extreme values compared with their median, which may indicate possible outliers. Examples include LotArea, GrLivArea, MiscVal, and SalePrice. GarageYrBlt also contains a suspicious maximum value of 2207, which should be investigated during preprocessing.

In [35]:
df["SalePrice"].sort_values().head()

495    34900.0
916    35311.0
968    37900.0
533    39300.0
30     40000.0
Name: SalePrice, dtype: float64

The lowest house prices range from 34,900 to 40,000. These values are much lower than the median price 176,735, so they should be kept in mind as possible low-end outliers, but they are not automatically errors.

In [36]:
df["SalePrice"].sort_values(ascending=False).head()

691     755000.0
1182    745000.0
1169    625000.0
898     611657.0
803     582933.0
Name: SalePrice, dtype: float64

The highest house prices range from 582 933 to 755 000. These values are much higher than the median price, so they may represent high-end outliers and should be analyzed further before deciding whether to keep, transform, or remove them.