In [15]:
import pandas as pd
df = pd.read_csv("../data/raw/House_Prices.csv")

In [5]:
df.shape

(2919, 81)

the data contains 2919 houses nad 81 feature

In [6]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='str')

the dataset contains many features describing the house : its locations , size , quality, age , rooms, garage, outdoor areas and sate info 
the target is SatePrice

In [34]:
pd.set_option('display.max_rows', None)
df.dtypes

Id                 int64
MSSubClass         int64
MSZoning             str
LotFrontage      float64
LotArea            int64
Street               str
Alley                str
LotShape             str
LandContour          str
Utilities            str
LotConfig            str
LandSlope            str
Neighborhood         str
Condition1           str
Condition2           str
BldgType             str
HouseStyle           str
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
RoofStyle            str
RoofMatl             str
Exterior1st          str
Exterior2nd          str
MasVnrType           str
MasVnrArea       float64
ExterQual            str
ExterCond            str
Foundation           str
BsmtQual             str
BsmtCond             str
BsmtExposure         str
BsmtFinType1         str
BsmtFinSF1       float64
BsmtFinType2         str
BsmtFinSF2       float64
BsmtUnfSF        float64
TotalBsmtSF      float64
Heating              str
HeatingQC            str
CentralAir           str
Electrical           str
1stFlrSF           int64
2ndFlrSF           int64
LowQualFinSF       int64
GrLivArea          int64
BsmtFullBath     float64
BsmtHalfBath     float64
FullBath           int64
HalfBath           int64
BedroomAbvGr       int64
KitchenAbvGr       int64
KitchenQual          str
TotRmsAbvGrd       int64
Functional           str
Fireplaces         int64
FireplaceQu          str
GarageType           str
GarageYrBlt      float64
GarageFinish         str
GarageCars       float64
GarageArea       float64
GarageQual           str
GarageCond           str
PavedDrive           str
WoodDeckSF         int64
OpenPorchSF        int64
EnclosedPorch      int64
3SsnPorch          int64
ScreenPorch        int64
PoolArea           int64
PoolQC               str
Fence                str
MiscFeature          str
MiscVal            int64
MoSold             int64
YrSold             int64
SaleType             str
SaleCondition        str
SalePrice        float64
dtype: object

the df contains both numirical and categorical features

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             2919 non-null   int64
 1   MSSubClass     2919 non-null   int64
 2   MSZoning       2915 non-null   str
 3   LotFrontage    2433 non-null   float64
 4   LotArea        2919 non-null   int64
 5   Street         2919 non-null   str
 6   Alley          198 non-null    str
 7   LotShape       2919 non-null   str
 8   LandContour    2919 non-null   str
 9   Utilities      2917 non-null   str
 10  LotConfig      2919 non-null   str
 11  LandSlope      2919 non-null   str
 12  Neighborhood   2919 non-null   str
 13  Condition1     2919 non-null   str
 14  Condition2     2919 non-null   str
 15  BldgType       2919 non-null   str
 16  HouseStyle     2919 non-null   str
 17  OverallQual    2919 non-null   int64
 18  OverallCond    2919 non-null   int64
 19  YearBuilt      2919 non-null   int64
 20  YearRemodAdd   2919 non-null   int64
 21  RoofStyle      2919 non-null   str
 22  RoofMatl       2919 non-null   str
 23  Exterior1st    2918 non-null   str
 24  Exterior2nd    2918 non-null   str
 25  MasVnrType     1153 non-null   str
 26  MasVnrArea     2896 non-null   float64
 27  ExterQual      2919 non-null   str
 28  ExterCond      2919 non-null   str
 29  Foundation     2919 non-null   str
 30  BsmtQual       2838 non-null   str
 31  BsmtCond       2837 non-null   str
 32  BsmtExposure   2837 non-null   str
 33  BsmtFinType1   2840 non-null   str
 34  BsmtFinSF1     2918 non-null   float64
 35  BsmtFinType2   2839 non-null   str
 36  BsmtFinSF2     2918 non-null   float64
 37  BsmtUnfSF      2918 non-null   float64
 38  TotalBsmtSF    2918 non-null   float64
 39  Heating        2919 non-null   str
 40  HeatingQC      2919 non-null   str
 41  CentralAir     2919 non-null   str
 42  Electrical     2918 non-null   str
 43  1stFlrSF       2919 non-null   int64
 44  2ndFlrSF       2919 non-null   int64
 45  LowQualFinSF   2919 non-null   int64
 46  GrLivArea      2919 non-null   int64
 47  BsmtFullBath   2917 non-null   float64
 48  BsmtHalfBath   2917 non-null   float64
 49  FullBath       2919 non-null   int64
 50  HalfBath       2919 non-null   int64
 51  BedroomAbvGr   2919 non-null   int64
 52  KitchenAbvGr   2919 non-null   int64
 53  KitchenQual    2918 non-null   str
 54  TotRmsAbvGrd   2919 non-null   int64
 55  Functional     2917 non-null   str
 56  Fireplaces     2919 non-null   int64
 57  FireplaceQu    1499 non-null   str
 58  GarageType     2762 non-null   str
 59  GarageYrBlt    2760 non-null   float64
 60  GarageFinish   2760 non-null   str
 61  GarageCars     2918 non-null   float64
 62  GarageArea     2918 non-null   float64
 63  GarageQual     2760 non-null   str
 64  GarageCond     2760 non-null   str
 65  PavedDrive     2919 non-null   str
 66  WoodDeckSF     2919 non-null   int64
 67  OpenPorchSF    2919 non-null   int64
 68  EnclosedPorch  2919 non-null   int64
 69  3SsnPorch      2919 non-null   int64
 70  ScreenPorch    2919 non-null   int64
 71  PoolArea       2919 non-null   int64
 72  PoolQC         10 non-null     str
 73  Fence          571 non-null    str
 74  MiscFeature    105 non-null    str
 75  MiscVal        2919 non-null   int64
 76  MoSold         2919 non-null   int64
 77  YrSold         2919 non-null   int64
 78  SaleType       2918 non-null   str
 79  SaleCondition  2919 non-null   str
 80  SalePrice      2919 non-null   float64
dtypes: float64(12), int64(26), str(43)
memory usage: 2.2 MB

several columns contain missing values such : lotfrontage and alley

In [18]:
df.isna().sum()

Id                  0
MSSubClass          0
MSZoning            4
LotFrontage       486
LotArea             0
Street              0
Alley            2721
LotShape            0
LandContour         0
Utilities           2
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         1
Exterior2nd         1
MasVnrType       1766
MasVnrArea         23
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           81
BsmtCond           82
BsmtExposure       82
BsmtFinType1       79
BsmtFinSF1          1
BsmtFinType2       80
BsmtFinSF2          1
BsmtUnfSF           1
TotalBsmtSF         1
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        2
BsmtHalfBath        2
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         1
TotRmsAbvGrd        0
Functional          2
Fireplaces          0
FireplaceQu      1420
GarageType        157
GarageYrBlt       159
GarageFinish      159
GarageCars          1
GarageArea          1
GarageQual        159
GarageCond        159
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           2909
Fence            2348
MiscFeature      2814
MiscVal             0
MoSold              0
YrSold              0
SaleType            1
SaleCondition       0
SalePrice           0
dtype: int64

In [19]:
missing_values = df.isna().sum()

missing_values[missing_values > 0].sort_values(ascending=False)

PoolQC          2909
MiscFeature     2814
Alley           2721
Fence           2348
MasVnrType      1766
FireplaceQu     1420
LotFrontage      486
GarageQual       159
GarageYrBlt      159
GarageCond       159
GarageFinish     159
GarageType       157
BsmtExposure      82
BsmtCond          82
BsmtQual          81
BsmtFinType2      80
BsmtFinType1      79
MasVnrArea        23
MSZoning           4
BsmtFullBath       2
Functional         2
BsmtHalfBath       2
Utilities          2
BsmtFinSF1         1
Exterior2nd        1
Exterior1st        1
Electrical         1
TotalBsmtSF        1
BsmtUnfSF          1
BsmtFinSF2         1
KitchenQual        1
GarageArea         1
GarageCars         1
SaleType           1
dtype: int64

the datasets contains many missing values columns: some has very high percentage of missing data: poolQC , miscfeature , alley , fence ... others has a low percentage of missing date different strategies will be needed during data processing

In [20]:
df.duplicated().sum()

np.int64(0)

no duplicateds rows found in the data

In [21]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,2919.000000,2919.000000,2433.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2896.000000,2918.000000,...,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000
mean,1460.000000,57.137718,69.305795,10168.114080,6.089072,5.564577,1971.312778,1984.264474,102.201312,441.423235,...,93.709832,47.486811,23.098321,2.602261,16.062350,2.251799,50.825968,6.213087,2007.792737,180052.854647
std,842.787043,42.517628,23.344905,7886.996359,1.409947,1.113131,30.291442,20.894344,179.334253,455.610826,...,126.526589,67.575493,64.244246,25.188169,56.184365,35.663946,567.402211,2.714762,1.314964,57381.565721
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,730.500000,20.000000,59.000000,7478.000000,5.000000,5.000000,1953.500000,1965.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,154795.084126
50%,1460.000000,50.000000,68.000000,9453.000000,6.000000,5.000000,1973.000000,1993.000000,0.000000,368.500000,...,0.000000,26.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,176734.841494
75%,2189.500000,70.000000,80.000000,11570.000000,7.000000,6.000000,2001.000000,2004.000000,164.000000,733.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,191895.744157
max,2919.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

The numerical features have very different ranges: Some columns show large extreme values, such as LotArea, which may indicate outliers. SalePrice ranges from 34 900 to 755 000, with a median around 176 735

In [18]:
numeric_cols = df.select_dtypes(include="number").columns
categorical_cols = df.select_dtypes(exclude="number").columns

In [21]:
numeric_cols
#len(numeric_cols)

Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'MiscVal', 'MoSold', 'YrSold', 'SalePrice'],
      dtype='str')

the dataset contains 38 numirical columns , most represent numirical values , but some are categorical codes and may require special handling

In [31]:
categorical_cols
#len(categorical_cols)

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='str')

The dataset contains 43 categorical columns. Most of them will need to be encoded into numerical values before they can be used by the Machine Learning models

In [29]:
df["SalePrice"].describe()

count      2919.000000
mean     180052.854647
std       57381.565721
min       34900.000000
25%      154795.084126
50%      176734.841494
75%      191895.744157
max      755000.000000
Name: SalePrice, dtype: float64

SalePrice has an average value of about 180,053 and a median of about 176,735. Prices range from 34,900 to 755,000, which shows a wide spread and suggests the presence of some high-price extreme values.

In [35]:
for col in categorical_cols:
    print(col, df[col].unique()[:20])

MSZoning <ArrowStringArray>
['RL', 'RM', 'C (all)', 'FV', 'RH', nan]
Length: 6, dtype: str
Street <ArrowStringArray>
['Pave', 'Grvl']
Length: 2, dtype: str
Alley <ArrowStringArray>
[nan, 'Grvl', 'Pave']
Length: 3, dtype: str
LotShape <ArrowStringArray>
['Reg', 'IR1', 'IR2', 'IR3']
Length: 4, dtype: str
LandContour <ArrowStringArray>
['Lvl', 'Bnk', 'Low', 'HLS']
Length: 4, dtype: str
Utilities <ArrowStringArray>
['AllPub', 'NoSeWa', nan]
Length: 3, dtype: str
LotConfig <ArrowStringArray>
['Inside', 'FR2', 'Corner', 'CulDSac', 'FR3']
Length: 5, dtype: str
LandSlope <ArrowStringArray>
['Gtl', 'Mod', 'Sev']
Length: 3, dtype: str
Neighborhood <ArrowStringArray>
['CollgCr', 'Veenker', 'Crawfor', 'NoRidge', 'Mitchel', 'Somerst',  'NWAmes',
 'OldTown', 'BrkSide',  'Sawyer', 'NridgHt',   'NAmes', 'SawyerW',  'IDOTRR',
 'MeadowV', 'Edwards',  'Timber', 'Gilbert', 'StoneBr', 'ClearCr']
Length: 20, dtype: str
Condition1 <ArrowStringArray>
['Norm', 'Feedr', 'PosN', 'Artery', 'RRAe', 'RRNn', 'RRAn', 'PosA', 'RRNe']
Length: 9, dtype: str
Condition2 <ArrowStringArray>
['Norm', 'Artery', 'RRNn', 'Feedr', 'PosN', 'PosA', 'RRAn', 'RRAe']
Length: 8, dtype: str
BldgType <ArrowStringArray>
['1Fam', '2fmCon', 'Duplex', 'TwnhsE', 'Twnhs']
Length: 5, dtype: str
HouseStyle <ArrowStringArray>
['2Story', '1Story', '1.5Fin', '1.5Unf', 'SFoyer', 'SLvl', '2.5Unf', '2.5Fin']
Length: 8, dtype: str
RoofStyle <ArrowStringArray>
['Gable', 'Hip', 'Gambrel', 'Mansard', 'Flat', 'Shed']
Length: 6, dtype: str
RoofMatl <ArrowStringArray>
['CompShg', 'WdShngl',   'Metal', 'WdShake', 'Membran', 'Tar&Grv',    'Roll',
 'ClyTile']
Length: 8, dtype: str
Exterior1st <ArrowStringArray>
['VinylSd', 'MetalSd', 'Wd Sdng', 'HdBoard', 'BrkFace', 'WdShing', 'CemntBd',
 'Plywood', 'AsbShng',  'Stucco', 'BrkComm', 'AsphShn',   'Stone', 'ImStucc',
  'CBlock',       nan]
Length: 16, dtype: str
Exterior2nd <ArrowStringArray>
['VinylSd', 'MetalSd', 'Wd Shng', 'HdBoard', 'Plywood', 'Wd Sdng', 'CmentBd',
 'BrkFace',  'Stucco', 'AsbShng', 'Brk Cmn', 'ImStucc', 'AsphShn',   'Stone',
   'Other',  'CBlock',       nan]
Length: 17, dtype: str
MasVnrType <ArrowStringArray>
['BrkFace', nan, 'Stone', 'BrkCmn']
Length: 4, dtype: str
ExterQual <ArrowStringArray>
['Gd', 'TA', 'Ex', 'Fa']
Length: 4, dtype: str
ExterCond <ArrowStringArray>
['TA', 'Gd', 'Fa', 'Po', 'Ex']
Length: 5, dtype: str
Foundation <ArrowStringArray>
['PConc', 'CBlock', 'BrkTil', 'Wood', 'Slab', 'Stone']
Length: 6, dtype: str
BsmtQual <ArrowStringArray>
['Gd', 'TA', 'Ex', nan, 'Fa']
Length: 5, dtype: str
BsmtCond <ArrowStringArray>
['TA', 'Gd', nan, 'Fa', 'Po']
Length: 5, dtype: str
BsmtExposure <ArrowStringArray>
['No', 'Gd', 'Mn', 'Av', nan]
Length: 5, dtype: str
BsmtFinType1 <ArrowStringArray>
['GLQ', 'ALQ', 'Unf', 'Rec', 'BLQ', nan, 'LwQ']
Length: 7, dtype: str
BsmtFinType2 <ArrowStringArray>
['Unf', 'BLQ', nan, 'ALQ', 'Rec', 'LwQ', 'GLQ']
Length: 7, dtype: str
Heating <ArrowStringArray>
['GasA', 'GasW', 'Grav', 'Wall', 'OthW', 'Floor']
Length: 6, dtype: str
HeatingQC <ArrowStringArray>
['Ex', 'Gd', 'TA', 'Fa', 'Po']
Length: 5, dtype: str
CentralAir <ArrowStringArray>
['Y', 'N']
Length: 2, dtype: str
Electrical <ArrowStringArray>
['SBrkr', 'FuseF', 'FuseA', 'FuseP', 'Mix', nan]
Length: 6, dtype: str
KitchenQual <ArrowStringArray>
['Gd', 'TA', 'Ex', 'Fa', nan]
Length: 5, dtype: str
Functional <ArrowStringArray>
['Typ', 'Min1', 'Maj1', 'Min2', 'Mod', 'Maj2', 'Sev', nan]
Length: 8, dtype: str
FireplaceQu <ArrowStringArray>
[nan, 'TA', 'Gd', 'Fa', 'Ex', 'Po']
Length: 6, dtype: str
GarageType <ArrowStringArray>
['Attchd', 'Detchd', 'BuiltIn', 'CarPort', nan, 'Basment', '2Types']
Length: 7, dtype: str
GarageFinish <ArrowStringArray>
['RFn', 'Unf', 'Fin', nan]
Length: 4, dtype: str
GarageQual <ArrowStringArray>
['TA', 'Fa', 'Gd', nan, 'Ex', 'Po']
Length: 6, dtype: str
GarageCond <ArrowStringArray>
['TA', 'Fa', nan, 'Gd', 'Po', 'Ex']
Length: 6, dtype: str
PavedDrive <ArrowStringArray>
['Y', 'N', 'P']
Length: 3, dtype: str
PoolQC <ArrowStringArray>
[nan, 'Ex', 'Fa', 'Gd']
Length: 4, dtype: str
Fence <ArrowStringArray>
[nan, 'MnPrv', 'GdWo', 'GdPrv', 'MnWw']
Length: 5, dtype: str
MiscFeature <ArrowStringArray>
[nan, 'Shed', 'Gar2', 'Othr', 'TenC']
Length: 5, dtype: str
SaleType <ArrowStringArray>
['WD', 'New', 'COD', 'ConLD', 'ConLI', 'CWD', 'ConLw', 'Con', 'Oth', nan]
Length: 10, dtype: str
SaleCondition <ArrowStringArray>
['Normal', 'Abnorml', 'Partial', 'AdjLand', 'Alloca', 'Family']
Length: 6, dtype: str

No obvious inconsistencies were found in the categorical values. Most values appear to use consistent category codes. Some categorical columns contain missing values NaN, which will be handled during preprocessing

In [24]:
df[numeric_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
Id,2919.0,1460.000000,842.787043,1.0,730.500000,1460.000000,2189.500000,2919.0
MSSubClass,2919.0,57.137718,42.517628,20.0,20.000000,50.000000,70.000000,190.0
LotFrontage,2433.0,69.305795,23.344905,21.0,59.000000,68.000000,80.000000,313.0
LotArea,2919.0,10168.114080,7886.996359,1300.0,7478.000000,9453.000000,11570.000000,215245.0
OverallQual,2919.0,6.089072,1.409947,1.0,5.000000,6.000000,7.000000,10.0
OverallCond,2919.0,5.564577,1.113131,1.0,5.000000,5.000000,6.000000,9.0
YearBuilt,2919.0,1971.312778,30.291442,1872.0,1953.500000,1973.000000,2001.000000,2010.0
YearRemodAdd,2919.0,1984.264474,20.894344,1950.0,1965.000000,1993.000000,2004.000000,2010.0
MasVnrArea,2896.0,102.201312,179.334253,0.0,0.000000,0.000000,164.000000,1600.0
BsmtFinSF1,2918.0,441.423235,455.610826,0.0,0.000000,368.500000,733.000000,5644.0
BsmtFinSF2,2918.0,49.582248,169.205611,0.0,0.000000,0.000000,0.000000,1526.0
BsmtUnfSF,2918.0,560.772104,439.543659,0.0,220.000000,467.000000,805.500000,2336.0
TotalBsmtSF,2918.0,1051.777587,440.766258,0.0,793.000000,989.500000,1302.000000,6110.0
1stFlrSF,2919.0,1159.581706,392.362079,334.0,876.000000,1082.000000,1387.500000,5095.0
2ndFlrSF,2919.0,336.483727,428.701456,0.0,0.000000,0.000000,704.000000,2065.0
LowQualFinSF,2919.0,4.694416,46.396825,0.0,0.000000,0.000000,0.000000,1064.0
GrLivArea,2919.0,1500.759849,506.051045,334.0,1126.000000,1444.000000,1743.500000,5642.0
BsmtFullBath,2917.0,0.429894,0.524736,0.0,0.000000,0.000000,1.000000,3.0
BsmtHalfBath,2917.0,0.061364,0.245687,0.0,0.000000,0.000000,0.000000,2.0
FullBath,2919.0,1.568003,0.552969,0.0,1.000000,2.000000,2.000000,4.0
HalfBath,2919.0,0.380267,0.502872,0.0,0.000000,0.000000,1.000000,2.0
BedroomAbvGr,2919.0,2.860226,0.822693,0.0,2.000000,3.000000,3.000000,8.0
KitchenAbvGr,2919.0,1.044536,0.214462,0.0,1.000000,1.000000,1.000000,3.0
TotRmsAbvGrd,2919.0,6.451524,1.569379,2.0,5.000000,6.000000,7.000000,15.0
Fireplaces,2919.0,0.597122,0.646129,0.0,0.000000,1.000000,1.000000,4.0
GarageYrBlt,2760.0,1978.113406,25.574285,1895.0,1960.000000,1979.000000,2002.000000,2207.0
GarageCars,2918.0,1.766621,0.761624,0.0,1.000000,2.000000,2.000000,5.0
GarageArea,2918.0,472.874572,215.394815,0.0,320.000000,480.000000,576.000000,1488.0
WoodDeckSF,2919.0,93.709832,126.526589,0.0,0.000000,0.000000,168.000000,1424.0
OpenPorchSF,2919.0,47.486811,67.575493,0.0,0.000000,26.000000,70.000000,742.0
EnclosedPorch,2919.0,23.098321,64.244246,0.0,0.000000,0.000000,0.000000,1012.0
3SsnPorch,2919.0,2.602261,25.188169,0.0,0.000000,0.000000,0.000000,508.0
ScreenPorch,2919.0,16.062350,56.184365,0.0,0.000000,0.000000,0.000000,576.0
PoolArea,2919.0,2.251799,35.663946,0.0,0.000000,0.000000,0.000000,800.0
MiscVal,2919.0,50.825968,567.402211,0.0,0.000000,0.000000,0.000000,17000.0
MoSold,2919.0,6.213087,2.714762,1.0,4.000000,6.000000,8.000000,12.0
YrSold,2919.0,2007.792737,1.314964,2006.0,2007.000000,2008.000000,2009.000000,2010.0
SalePrice,2919.0,180052.854647,57381.565721,34900.0,154795.084126,176734.841494,191895.744157,755000.0

Several numerical features contain extreme values compared with their median, which may indicate possible outliers. Examples include LotArea, GrLivArea, MiscVal, and SalePrice. GarageYrBlt also contains a suspicious maximum value of 2207, which should be investigated during preprocessing.

In [25]:
df["SalePrice"].sort_values().head()

495    34900.0
916    35311.0
968    37900.0
533    39300.0
30     40000.0
Name: SalePrice, dtype: float64

The lowest house prices range from 34,900 to 40,000. These values are much lower than the median price (~176,735), so they should be kept in mind as possible low-end outliers, but they are not automatically errors.

In [26]:
df["SalePrice"].sort_values(ascending=False).head()

691     755000.0
1182    745000.0
1169    625000.0
898     611657.0
803     582933.0
Name: SalePrice, dtype: float64

The highest house prices range from 582,933 to 755,000. These values are much higher than the median price, so they may represent high-end outliers and should be analyzed further before deciding whether to keep, transform, or remove them.